const {chromium}=require('C:/Users/Chris/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs');const path=require('path');const assert=require('assert');
const root=path.resolve(__dirname,'../..');
const output=path.join(root,'Verification/arcade-s5-music-audit-20260926/Viewer');
const target='http://127.0.0.1:8769/';
const tracks=JSON.parse(fs.readFileSync(path.join(output,'tracks.json'),'utf8'));
const total=tracks.length;
assert(tracks.every(t=>t.game==='The Arcade · Season 5'));
assert.equal(total,74);
assert(tracks.every(t=>!['Menu music','Additional BGM','Story music','Unlisted songs','Movie audio'].includes(t.category)));
let runningBrowser;
(async()=>{
 const browser=await chromium.launch({executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe',headless:true});
 runningBrowser=browser;
 const context=await browser.newContext({viewport:{width:1440,height:1000}});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(target);await page.waitForSelector('body.js');
 await page.screenshot({path:path.join(output,'desktop-preview.png'),fullPage:false});
 assert.equal(await page.locator('.track-row:visible').count(),total);
 assert.equal(await page.locator('#game').count(),0);
 await page.locator('#play').click();
 await page.waitForFunction(()=>document.getElementById('player-audio').currentTime>.3);
 assert.equal(await page.locator('#play').getAttribute('aria-label'),'Pause preview');
 await page.locator('#seek').fill('12');
 await page.waitForFunction(()=>document.getElementById('player-audio').currentTime>=11.5);
 await page.locator('#next').click();
 await page.waitForFunction(()=>document.getElementById('player-title').textContent==='Waiting for you'&&!document.getElementById('player-audio').paused);
 await page.locator('#play').click();
 assert(await page.locator('#player-audio').evaluate(e=>e.paused));
 await page.locator('#favorite').click();
 await page.locator('[data-library="favorites"]').click();
 assert.equal(await page.locator('.track-row:visible').count(),1);
 await page.reload();await page.waitForSelector('body.js');
 assert.equal(await page.locator('#favorite-count').innerText(),'1');
 assert.equal(await page.locator('#player-title').innerText(),'Waiting for you');
 await page.locator('[data-category="Project DIVA"]').click();
 assert.equal(await page.locator('.track-row:visible').count(),12);
 await page.locator('#search').fill('ロキ');
 assert.equal(await page.locator('.track-row:visible').count(),1);
 await page.locator('.track-row:visible .row-play').click();
 await page.waitForFunction(()=>document.getElementById('player-audio').currentTime>.2);
 await page.locator('#play').click();
 await page.locator('#search').fill('nothing should match this 918273');
 assert(await page.locator('#empty').isVisible());
 await page.locator('#clear-search').click();
 assert.equal(await page.locator('.track-row:visible').count(),total);
 // Play a sample from every newly included kind of Season 5 music.
 for(const category of ['The Arcade originals','Touhou Project','Project DIVA','MF Ghost']){
  await page.locator(`[data-category="${category}"]`).click();
  assert.equal(await page.locator('.track-row:visible').count(),tracks.filter(t=>t.category===category).length);
  const selection=page.locator('.track-row:visible').first();
  await selection.locator('.row-play').click();
  await page.waitForFunction(()=>document.getElementById('player-audio').currentTime>.2);
  await page.locator('#play').click();
  assert.equal(await page.locator('#mobile-category').inputValue(),category);
 }
 await page.locator('[data-library="all"]').click();
 assert.equal(await page.locator('.track-row:visible').count(),total);
 await page.locator('#sort').selectOption('duration');
 const lengths=await page.locator('.track-row:visible .row-duration').allTextContents();
 const seconds=lengths.map(t=>t.split(':').reduce((a,n)=>a*60+Number(n),0));
 assert(seconds.every((x,i)=>i===0||x>=seconds[i-1]));
 await page.locator('#volume').fill('0.21');
 assert(Math.abs(await page.locator('#player-audio').evaluate(e=>e.volume)-.21)<.001);
 await page.locator('#mute').click();assert(await page.locator('#player-audio').evaluate(e=>e.muted));
 await page.locator('#play').click();
 await page.waitForFunction(()=>document.getElementById('player-audio').readyState>=2);
 await page.locator('#player-audio').evaluate(e=>{e.currentTime=e.duration-.12});
 await page.waitForFunction(()=>document.getElementById('player-audio').ended);
 assert.equal(await page.locator('#playback-status').innerText(),'Preview finished');
 await page.evaluate(()=>localStorage.clear());await page.reload();
 await page.locator('.row-info').filter({hasText:'Dive into the SPEED'}).click();
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(output,'desktop-preview.png'),fullPage:false});
 await page.setViewportSize({width:390,height:844});
 await page.evaluate(()=>scrollTo(0,0));
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.screenshot({path:path.join(output,'mobile-preview.png'),fullPage:false});
 await page.locator('#mobile-category').selectOption('Touhou Project');
 assert.equal(await page.locator('.track-row:visible').count(),25);
 await page.locator('#mobile-favorites').click();assert(await page.locator('#empty').isVisible());
 await page.locator('#clear-search').click();
 await page.locator('#mobile-category').selectOption('Project DIVA');
 assert.equal(await page.locator('.track-row:visible').count(),12);
 await page.setViewportSize({width:320,height:740});
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('#mobile-category').selectOption('all');
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:path.join(output,'mobile-320-preview.png'),fullPage:false});
 // The downloadable file embeds its media and plays without a local server.
 const portable=await context.newPage();portable.on('pageerror',e=>errors.push(e.message));
 await portable.goto('file:///'+path.join(output,'Sound Room.html').replaceAll('\\','/'));await portable.waitForSelector('body.js');
 await portable.locator('#play').click();
 assert.equal(await portable.locator('.track-row').count(),total);
 // Previously saved entries from other games must not restore those games into this library.
 const migration=await context.newPage();
 await migration.addInitScript(()=>localStorage.setItem('initial-d-season5-sound-room-v1',JSON.stringify({selected:'stage3.01_gamble_rumble',favorites:['stage3.01_gamble_rumble','A_ONE_01'],volume:.4})));
 await migration.goto(target);await migration.waitForSelector('body.js');
 assert.equal(await migration.locator('#player-title').innerText(),'Dive into the SPEED');
 assert.equal(await migration.locator('#favorite-count').innerText(),'1');
 await migration.close();
 await portable.waitForFunction(()=>document.getElementById('player-audio').currentTime>.3);
 assert((await portable.locator('#player-audio').getAttribute('src')).startsWith('data:audio/mpeg;base64,'));
 await portable.locator('#play').click();
 // JavaScript-disabled fallback retains native playable audio controls.
 const native=await browser.newContext({javaScriptEnabled:false,viewport:{width:390,height:844}});
 const fallback=await native.newPage();await fallback.goto(target);
 assert.equal(await fallback.locator('audio.fallback-audio:visible').count(),total);
 assert.equal(await fallback.locator('.track-row:visible').count(),total);
 assert.equal(errors.length,0,errors.join('\n'));
 const report={passed:true,tracks:total,game:'The Arcade Season 5',categoryCounts:{projectDiva:12,touhou:25,originals:25},checks:['74 named race songs present','other games excluded','excluded non-race collections absent','pause and seek','next track while playing','favorites persistence and old-library migration','Japanese search','no-result recovery','duration sorting','volume and mute','end-of-preview state','mobile categories/favorites','390px and 320px overflow','offline embedded-audio playback',`${total} native audio controls with JavaScript disabled`],pageErrors:errors};
 fs.writeFileSync(path.join(output,'ui-checks.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report));await browser.close();
})().catch(async e=>{console.error(e);if(runningBrowser)await runningBrowser.close();process.exitCode=1});
